site_name: Geo Bharat
site_url : https://geobharat.github.io/
theme:
  name: material
  custom_dir: docs/overrides/
  logo: assets/images/gb.png
  palette:
    primary: custom
  favicon: assets/images/gb.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  # features:
  #   - announce.dismiss

nav:
  - ğŸ  Home : index.md
  - ğŸ—£ï¸ Talks : 
    - pages/talks/index.md
    - 31-12-2023 : pages/talks/31-12-2023.md
    - 13-01-2024 : pages/talks/13-01-2024.md
    - 27-01-2024 : pages/talks/27-01-2024.md
    - 10-02-2024 : pages/talks/10-02-2024.md
  - ğŸ’» Workshop : 
    - pages/workshop/index.md
  - ğŸ¤ğŸ» Help : help.md

markdown_extensions:
  - meta
  - tables
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geobharat
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCyh9f6Y6XF6W4cGWo_W1ENg
    - icon: fontawesome/brands/telegram
      link: https://t.me/geobharat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/geo-bharat
  variables:
    - ytwidth : 1000
    - ytheight : 1000
  analytics:
    provider: google
    property: G-3B75HL0FJ9

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js



